"""add exit_word column

Revision ID: b6df2e975d7a
Revises: 046451e1f76d
Create Date: 2026-02-17 18:31:15.507929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6df2e975d7a'
down_revision: Union[str, None] = '046451e1f76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exit_word', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exit_word')
    # ### end Alembic commands ###
